---
# tasks file for postfix-satellite/debian.yml
    
- name: install postfix (apt)
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - "postfix"
  tags: postfix-satellite
  