---
# tasks file for postfix-satellite/debian.yml
    
- name: install postfix (apt)
  apt:
    name: "{{ satellite_packages }}"
    state: latest
    install_recommends: no
  tags: postfix-satellite
  