---
# tasks file for postfix-satellite/main.yml

- name: gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "main.yml"
      paths:
        - "vars"
  tags: postfix-satellite

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: install postfix config from template
  template:
    src: "postfix_main_cf.j2"
    dest: "/etc/postfix/main.cf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - restart postfix
  tags: postfix-satellite

- name: configure aliases database
  template:
    src: "aliases.j2"
    dest: "/etc/aliases"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - newaliases
  tags: postfix-satellite

#- name: remove smtp_fallback_relay
#  when:
#    - postfix_conf.smtp_tls is defined
#  tags: postfix-satellite

- name: create sasl_passwd
  template:
    src: "sasl_passwd.j2"
    dest: "{{ sasl_passwd }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when:
    - postfix_conf.smtp_tls is defined
    - postfix_conf.smtp_sasl is defined
  notify:
    - postmap sasl_passwd
    - update ca-certificates
    - restart postfix
  tags: postfix-satellite

- name: postmap sasl_passwd
  command: "/usr/sbin/postmap hash:{{ sasl_passwd }}"
  changed_when: false
  when:
    - postfix_conf.smtp_tls is defined
    - postfix_conf.smtp_sasl is defined
  tags: postfix-satellite

- name: set permissions on {{ sasl_passwd }}
  file:
    path: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0600"
  loop: "{{ sasl_conf }}"
  when:
    - postfix_conf.smtp_tls is defined
    - postfix_conf.smtp_sasl is defined
  tags: postfix-satellite

- name: set permissions on /etc/postfix/sasl directory
  file:
    path: "/etc/postfix/sasl"
    owner: "root"
    group: "root"
    mode: "0700"
  when:
    - postfix_conf.smtp_tls is defined
    - postfix_conf.smtp_sasl is defined
  tags: postfix-satellite

- name: create generic table
  template:
    src: "generic.j2"
    dest: "{{ generic_table }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - postfix_conf.generic_table is defined
  notify:
    - postmap generic
    - restart postfix
