---
# tasks file for postfix-satellite/main.yml

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: postfix-satellite

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
  
- name: install postfix config from template
  template:
    src: "postfix_main_cf.j2"
    dest: "/etc/postfix/main.cf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - restart postfix
  tags: postfix-satellite

- name: configure aliases database
  template:
    src: "aliases.j2"
    dest: "/etc/aliases"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 
    - newaliases
  tags: postfix-satellite

#- name: remove smtp_fallback_relay
#  when:
#    - postfix_conf.smtp_tls is defined 
#  tags: postfix-satellite

- name: create sasl_passwd
  template:
    src: "sasl_passwd.j2"
    dest: "{{ sasl_passwd }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when:
    - postfix_conf.smtp_tls is defined 
    - postfix_conf.smtp_tls == true
  notify:
    - hash sasl_passwd
    - update ca-certificates
    - restart postfix
  tags: postfix-satellite

- name: hash sasl_passwd
  command: "/usr/sbin/postmap hash:{{ sasl_passwd }}"
  when:
    - postfix_conf.smtp_tls is defined 
    - postfix_conf.smtp_tls == true
  tags: postfix-satellite

- name: set permissions on sasl_passwd
  file:
    path: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0600"
  loop: "{{ sasl_conf }}"
  when:
    - postfix_conf.smtp_tls is defined 
    - postfix_conf.smtp_tls == true
  tags: postfix-satellite 
