---
# tasks file for ansible-role-postfix-satellite — Suse/openSUSE

- name: Install postfix (zypper)
  community.general.zypper:
    name: "{{ postfix_satellite_packages }}"
    state: "present"
  tags: postfix-satellite

- name: Install postfix SASL packages (zypper)
  community.general.zypper:
    name: "{{ postfix_satellite_sasl_packages }}"
    state: "present"
  when:
    - postfix_conf is defined
    - postfix_conf.smtp_sasl is defined
  tags: postfix-satellite
