---
# handlers file for ansible-role-postfix-satellite

- name: Restart postfix
  ansible.builtin.service:
    name: "postfix"
    state: restarted
  tags: postfix-satellite

- name: Reload postfix
  ansible.builtin.service:
    name: "postfix"
    state: "reloaded"
  tags: postfix-satellite

- name: Newaliases
  ansible.builtin.command: "/usr/bin/newaliases"
  changed_when: false
  tags: postfix-satellite

- name: Postmap sasl_passwd
  ansible.builtin.command: "/usr/sbin/postmap hash:{{ sasl_passwd }}"
  changed_when: false
  tags: postfix-satellite

- name: Update ca-certificates
  ansible.builtin.command: "/usr/sbin/update-ca-certificates"
  changed_when: false
  tags: postfix-satellite

- name: Postmap generic
  ansible.builtin.command: "/usr/sbin/postmap hash:{{ generic_table }}"
  changed_when: false
  tags: postfix-satellite
