---
# handlers file for roles/postfix-satellite

- name: restart postfix
  service:
    name: "postfix"
    state: restarted
  tags: postfix-satellite

- name: reload postfix
  service:
    name: "postfix"
    state: "reloaded"
  tags: postfix-satellite
    
- name: newaliases
  command: "/usr/bin/newaliases"
  tags: postfix-satellite

- name: hash sasl_passwd
  command: "/usr/sbin/postmap hash:{{ sasl_passwd }}"
  tags: postfix-satellite

- name: update ca-certificates
  command: "/usr/sbin/update-ca-certificates"
  tags: postfix-satellite
