---
- name: Converge
  hosts: all
  become: true

  vars:
    postfix_conf:
      admin_email: postmaster@localhost
      myhostname: localhost
      myorigin: localhost
      relayhost: relay.localhost
      relayport: "587"
      compatibility_level: "2"
      lmtp_host_lookup: native
      smtp_host_lookup: native
      smtp_tls: true
      smtp_sasl:
        - username: users1
          password: password1
        - username: user2
          password: password2
        - username: user3
          password: password3
      generic_table:
        - pattern: "@hostname.domain.com"
          result: "noreply@domain.com"
        - pattern: "@domain.com"
          result: "noreply@domain.com"

    aws_ses:
      username: "username"
      password: "passwd"

  environment:
    TZ: "America/Chicago" # Keep tzdata pacakge happy
    DEBIAN_FRONTEND: "noninteractive"

  pre_tasks:
    - name: PRE-TASK update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: real_time_com.postfix-satellite
