---
- name: Molecule converge
  hosts: all
  become: true

  vars:
    postfix_conf:
      admin_email: postmaster@localhost
      myhostname: Localhost
      myorigin: localhost
      relayhost: relay.localhost
      relayport: "587"
      compatibility_level: "2"
      lmtp_host_lookup: native
      smtp_host_lookup: native
      smtp_tls: true
      smtp_sasl:
        - username: Users1
          password: password1
        - username: User2
          password: password2
        - username: User3
          password: password3
      generic_table:
        - pattern: "@hostname.domain.com"
          result: "noreply@domain.com"
        - pattern: "@domain.com"
          result: "noreply@domain.com"

  environment:
    TZ: "America/Chicago"    # Keep tzdata pacakge happy
    DEBIAN_FRONTEND: "noninteractive"

  pre_tasks:

  roles:
  # - role: postfix_satellite
