---
- name: Molecule converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
      changed_when: false
      when: ansible_facts.os_family == 'Debian'
    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_facts.os_family == 'RedHat'

  vars:
    postfix_conf:
      admin_email: postmaster@localhost
      myhostname: localhost
      myorigin: localhost
      relayhost: relay.localhost
      relayport: "587"
      compatibility_level: "3.6"
      lmtp_host_lookup: native
      smtp_host_lookup: native
      smtp_tls: true
      smtp_sasl:
        - username: user1
          password: password1
        - username: user2
          password: password2
      generic_table:
        - pattern: "@hostname.example.com"
          result: "noreply@example.com"
        - pattern: "@example.com"
          result: "noreply@example.com"

  environment:
    TZ: "America/Chicago"
    DEBIAN_FRONTEND: "noninteractive"

  roles:
    - role: realtime.postfix_satellite
